# Remap the prefix from Ctrl+b to Ctrl+t
unbind C-b
set-option -g prefix C-t
bind-key C-t send-prefix

# Use Alt+\ and Alt+Shift+\ for splitting panes.
bind -n M-\\ split-window -h -c "#{pane_current_path}"
bind -n M-| split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Reload config file.
bind r source-file ~/.config/tmux/tmux.conf

# Bind arrow keys to pane switching.
bind -n M-left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Configure for use with Neovim.
set-option -g focus-events on

# Enable mouse usage.
set -g mouse on

