# Remap the prefix from Ctrl+b to Ctrl+t
unbind C-b
set-option -g prefix C-t
bind-key C-t send-prefix

# Use Alt+\ and Alt+Shift+\ for splitting panes.
bind -n M-\\ split-window -h
bind -n M-| split-window -v
unbind '"'
unbind %

# Reload config file.
bind r source-file ~/.config/tmux/tmux.conf

# Bind arrow keys to pane switching.
bind -n M-left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
