config-version = 2

accordion-padding = 30
auto-reload-config = true
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
focus-follows-mouse.enabled = true
on-focus-changed = ["move-mouse window-lazy-center"]
on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]
persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]
start-at-login = true

[exec]
inherit-env-vars = true

[key-mapping]
preset = "qwerty"

[mode.main.binding]
cmd-alt-1 = "workspace 1"
cmd-alt-2 = "workspace 2"
cmd-alt-3 = "workspace 3"
cmd-alt-4 = "workspace 4"
cmd-alt-5 = "workspace 5"
cmd-alt-6 = "workspace 6"
cmd-alt-7 = "workspace 7"
cmd-alt-8 = "workspace 8"
cmd-alt-9 = "workspace 9"
cmd-alt-0 = "workspace 10"

cmd-alt-shift-1 = "move-node-to-workspace 1 --focus-follows-window"
cmd-alt-shift-2 = "move-node-to-workspace 2 --focus-follows-window"
cmd-alt-shift-3 = "move-node-to-workspace 3 --focus-follows-window"
cmd-alt-shift-4 = "move-node-to-workspace 4 --focus-follows-window"
cmd-alt-shift-5 = "move-node-to-workspace 5 --focus-follows-window"
cmd-alt-shift-6 = "move-node-to-workspace 6 --focus-follows-window"
cmd-alt-shift-7 = "move-node-to-workspace 7 --focus-follows-window"
cmd-alt-shift-8 = "move-node-to-workspace 8 --focus-follows-window"
cmd-alt-shift-9 = "move-node-to-workspace 9 --focus-follows-window"
cmd-alt-shift-10 = "move-node-to-workspace 10 --focus-follows-window"

cmd-alt-b = "exec-and-forget /bin/zsh -lc 'open -n -b \"$AERO_BROWSER\"'"
cmd-alt-e = "exec-and-forget osascript -e 'tell application \"Finder\"' -e 'make new Finder window' -e 'activate' -e 'end tail'"
cmd-alt-f = "layout floating window"
cmd-alt-g = "exec-and-forget /bin/zsh -lc 'screencapture -i \"$HOME/Pictures/Screenshot_$(date +%Y-%m-%d_%H.%M.%S).png\"'"
cmd-alt-shift-g = "exec-and-forget screencapture -ic"
cmd-alt-j = "layout horizontal vertical"
cmd-alt-l = "exec-and-forget osascript -e 'tell application \"System Events\" to keystroke \"q\" using {control down, command down}'"
cmd-alt-o = "exec-and-forget open -a Obsidian"
cmd-alt-q = "close --quit-if-last-window"
cmd-alt-t = "exec-and-forget /bin/zsh -lc 'open -n -b \"$AERO_TERMINAL\"'"

cmd-alt-down = "focus down"
cmd-alt-left = "focus left"
cmd-alt-right = "focus right"
cmd-alt-up = "focus up"

cmd-alt-shift-down = "move down"
cmd-alt-shift-left = "move left"
cmd-alt-shift-right = "move right"
cmd-alt-shift-up = "move up"
