add_newline = false

[bun]
disabled = true

[cmd_duration]
disabled = true

[dotnet]
disabled = true

[java]
disabled = true

[line_break]
disabled = true

[nix_shell]
format = "[$symbol]($style)"
symbol = "❄️"

[nodejs]
disabled = true

[package]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true
